SPOTS = [
    {
        "name": "Uluwatu Suluban",
        "lat": -8.8187,
        "lng": 115.0889,
        "offshore": 90,
        "swell_min": 190,
        "swell_max": 260,
        "tide": "mid",
        "url": "https://maps.app.goo.gl/wiWCN1g8XfyGSbA67",
    },
    {
        "name": "Canggu Batu Bolong",
        "lat": -8.6512,
        "lng": 115.1385,
        "offshore": 90,
        "swell_min": 200,
        "swell_max": 270,
        "tide": "mid",
        "url": "https://maps.app.goo.gl/KixAhnWtvi9pFkd88",
    },
    {
        "name": "Kuta Beach",
        "lat": -8.7177,
        "lng": 115.1682,
        "offshore": 90,
        "swell_min": 200,
        "swell_max": 270,
        "tide": "mid",
        "url": "https://maps.app.goo.gl/efe821q2A9tCJv769",
    },
    {
        "name": "Medewi Beach",
        "lat": -8.4263,
        "lng": 114.7867,
        "offshore": 120,
        "swell_min": 210,
        "swell_max": 280,
        "tide": "high",
        "url": "https://maps.app.goo.gl/axWGQNZFdVA9JqhZA",
    },
]